create database projeto_dados;
use projeto_dados;

CREATE TABLE INSTITUICAO (
    ID_INSTITUICAO INT AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CAUSA_SOCIAL VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    ID_PLANO INT,
    DURACAO_PLANO VARCHAR(100),
    DATA_AQUISICAO_PLANO DATE,
    ESPACO_USUARIO_PLANO VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID_INSTITUICAO)
);

CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT,
    ID_INSTITUICAO INT,
    LOGIN VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DATA_INGRESSO DATE,
    PRIMARY KEY(ID_USUARIO),
    FOREIGN KEY (ID_INSTITUICAO) REFERENCES INSTITUICAO(ID_INSTITUICAO)
);

CREATE TABLE ADMINISTRADOR (
    ID_ADMIN INT AUTO_INCREMENT,
	ID_INSTITUICAO INT,
    LOGIN VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DATA_INGRESSO DATE,
    PRIMARY KEY(ID_ADMIN),
    FOREIGN KEY (ID_INSTITUICAO) REFERENCES INSTITUICAO(ID_INSTITUICAO)
);

CREATE TABLE ARQUIVO (
    ID_ARQUIVO INT AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_ADMIN INT,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    PERMISSAO_ACESSO VARCHAR(100) NOT NULL,
    TAMANHO DOUBLE NOT NULL,
    DATA_MODIFICACAO DATE,
    LOCALIZACAO VARCHAR(100) NOT NULL,
    URL VARCHAR(100) NOT NULL,
    CONTEUDO VARCHAR(255),
    PRIMARY KEY(ID_ARQUIVO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_ADMIN) REFERENCES ADMINISTRADOR(ID_ADMIN)
);

CREATE TABLE SUPORTE (
    ID_SUPORTE INT AUTO_INCREMENT,
    ID_ARQUIVO INT,
    ID_USUARIO INT,
    ID_ADMIN INT,
    DATA_PEDIDO DATETIME,
    DESCRICAO_SUPORTE VARCHAR(200),
    PRIMARY KEY(ID_SUPORTE),
    FOREIGN KEY (ID_ARQUIVO) REFERENCES ARQUIVO(ID_ARQUIVO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_ADMIN) REFERENCES ADMINISTRADOR(ID_ADMIN)
);

CREATE TABLE OPERAR (
	ID_OPERACAO INT AUTO_INCREMENT,
    TIPO_OPERACAO INT NOT NULL,
    DATA_OPERACAO DATE NOT NULL,
    ID_ARQUIVO INT,
    ID_USUARIO INT,
    PRIMARY KEY(ID_OPERACAO),
    FOREIGN KEY (ID_ARQUIVO) REFERENCES ARQUIVO(ID_ARQUIVO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE COMPARTILHAR (
    ID_COMPARTILHAMENTO INT AUTO_INCREMENT,
    ID_DONO INT,
    ID_RECEPTOR INT,
    ID_ARQUIVO INT,
    DATA_COMPARTILHAMENTO DATETIME NOT NULL,
    PRIMARY KEY(ID_COMPARTILHAMENTO),
    FOREIGN KEY (ID_DONO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_RECEPTOR) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_ARQUIVO) REFERENCES ARQUIVO(ID_ARQUIVO)
);

CREATE TABLE COMENTAR (
    CONTEUDO TEXT NOT NULL,
    DATA_COMENTARIO DATE NOT NULL,
    USUARIO_ID INT,
    ARQUIVO_ID INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ARQUIVO_ID) REFERENCES ARQUIVO(ID_ARQUIVO)
);

CREATE TABLE HISTORICO_VERSIONAMENTO (
    ID_HISTORICO INT AUTO_INCREMENT,
    ID_ARQUIVO INT,
    ID_USUARIO INT,
    OPERACAO INT,
    DATA_VERSIONAMENTO DATE,
    DATA_INGRESSO DATETIME NOT NULL,
    PRIMARY KEY(ID_HISTORICO),
    FOREIGN KEY (ID_ARQUIVO) REFERENCES ARQUIVO(ID_ARQUIVO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (OPERACAO) REFERENCES OPERAR(TIPO_OPERACAO)
);
