SELECT
	S.ID_SUPORTE,
    S.DESCRICAO_SUPORTE,
    AD.LOGIN AS NOME
FROM SUPORTE S
	INNER JOIN ADMINISTRADOR AD ON S.ID_ADMIN = AD.ID_ADMIN
    INNER JOIN USUARIO U ON S.ID_USUARIO = U.ID_USUARIO
    WHERE S.ID_USUARIO = @ID_USUARIO;


/* ⁠script para pedir suporte a um admi */
INSERT INTO SUPORTE (ID_ARQUIVO, ID_USUARIO, ID_ADMIN, DESCRICAO_SUPORTE)
VALUES (@ID_ARQUIVO, @ID_USUARIO, @ID_ADMIN, @DESCRICAO_SUPORTE);
    
/* script para mostrar os dados de um usuário */
SELECT
	U.LOGIN,
    U.ID_USUARIO,
    U.DATA_INGRESSO,
    U.EMAIL,
    U.SENHA,
    I.NOME AS 'NOME INSTITUICAO',
    I.ID_PLANO
FROM USUARIO U
	INNER JOIN INSTITUICAO I ON U.ID_INSTITUICAO = I.ID_INSTITUICAO
    WHERE U.ID_USUARIO = @ID_USUARIO;
    	
/* ⁠script para editar os dados de um usuário */
UPDATE USUARIO
SET LOGIN = @LOGIN,
	EMAIL = @EMAIL,
    SENHA = @SENHA
WHERE ID_USUARIO = @ID_USUARIO; 
