-- INSERE UM NOVO ARQUIVO NA TABELA 'ARQUIVO'
INSERT INTO ARQUIVO (ID_USUARIO, NOME, TIPO, PERMISSAO_ACESSO, DATA_MODIFICACAO, TAMANHO, LOCALIZACAO, URL, CONTEUDO) 
VALUES (@ID_USUARIO, @NOME, @TIPO, @PERMISSAO_ACESSO, @DATA_MODIFICACAO, @TAMANHO, @LOCALIZACAO, @URL, @CONTEUDO);
