-- INSERE UM NOVO COMENTARIO NA TABELA 'COMENTAR'
INSERT INTO COMENTAR (CONTEUDO, DATA_COMENTARIO, USUARIO_ID, ARQUIVO_ID) 
VALUES (@CONTEUDO, @DATA_COMENTARIO, @ID_USUARIO, 
        (SELECT ID_ARQUIVO FROM ARQUIVO WHERE NOME = @NOME));