-- INSERE UM NOVO PEDIDO DE SUPORTE NA TABELA 'SUPORTE'
INSERT INTO SUPORTE (ID_ARQUIVO, ID_USUARIO, ID_ADMIN, DESCRICAO_SUPORTE, DATA_PEDIDO)
VALUES (@ID_ARQUIVO, @ID_USUARIO, @ID_ADMIN, @DESCRICAO_SUPORTE, @DATA_PEDIDO);