-- RETORNA UM ARQUIVO PERTENCENTE A UMA INSTITUICAO
SELECT A.ID_ARQUIVO, A.ID_USUARIO, A.NOME, A.TIPO, A.PERMISSAO_ACESSO, 
       A.DATA_MODIFICACAO, A.TAMANHO, A.LOCALIZACAO, A.URL, A.CONTEUDO, U.LOGIN 
FROM ARQUIVO A 
LEFT JOIN USUARIO U ON U.ID_USUARIO = A.ID_USUARIO 
WHERE A.NOME = @NOME;