-- RETORNA TODAS AS VERSOES DE UM ARQUIVO NA TABELA 'HISTORICO_VERSIONAMENTO'
SELECT (SELECT COUNT(*) FROM HISTORICO_VERSIONAMENTO HV 
        WHERE HV.ID_ARQUIVO = H.ID_ARQUIVO AND HV.ID_HISTORICO <= H.ID_HISTORICO) AS VERSAO, 
        H.OPERACAO, H.CONTEUDO, H.DATA_VERSIONAMENTO 
FROM HISTORICO_VERSIONAMENTO H 
LEFT JOIN ARQUIVO A ON A.ID_ARQUIVO = H.ID_ARQUIVO 
WHERE H.ID_ARQUIVO = @ID_ARQUIVO 
ORDER BY H.DATA_VERSIONAMENTO DESC;