-- RETORNA UMA LISTA DE TODOS OS ARQUIVOS PERTENCENTES A UM USUARIO
SELECT ID_ARQUIVO, NOME, PERMISSAO_ACESSO, DATA_MODIFICACAO, TAMANHO, LOCALIZACAO, URL
FROM ARQUIVO 
WHERE ID_USUARIO = @ID_USUARIO;
