SELECT ARQUIVO.NOME AS NOME_ARQUIVO, ARQUIVO.TIPO AS TIPO, COMPARTILHAR.DATA_COMPARTILHAMENTO AS DATA_RECEBIMENTO, USUARIO.LOGIN AS NOME_DONO
FROM COMPARTILHAR
JOIN ARQUIVO ON COMPARTILHAR.ID_ARQUIVO = ARQUIVO.ID_ARQUIVO
JOIN USUARIO ON COMPARTILHAR.ID_DONO = USUARIO.ID_USUARIO
WHERE COMPARTILHAR.ID_RECEPTOR = @ID_USUARIO;
