-- RETORNA TODOS OS ARQUIVOS QUE UM USUARIO COMPARTILHOU
SELECT ARQUIVO.NOME AS NOME_ARQUIVO, ARQUIVO.TIPO AS TIPO, COMPARTILHAR.DATA_COMPARTILHAMENTO AS DATA_COMPARTILHAMENTO, USUARIO.LOGIN AS NOME_RECEPTOR
FROM COMPARTILHAR
JOIN ARQUIVO ON COMPARTILHAR.ID_ARQUIVO = ARQUIVO.ID_ARQUIVO
JOIN USUARIO ON COMPARTILHAR.ID_RECEPTOR = USUARIO.ID_USUARIO
WHERE COMPARTILHAR.ID_DONO = @ID_DONO;
