-- RETORNA O ULTIMO ARQUIVO CRIADO/EDITADO POR UM USUARIO NA TABELA 'ARQUIVO'
SELECT ID_ARQUIVO, ID_USUARIO, NOME, TIPO, PERMISSAO_ACESSO, 
       DATA_MODIFICACAO, TAMANHO, LOCALIZACAO, URL, CONTEUDO 
FROM ARQUIVO WHERE 
ID_USUARIO = @ID_USUARIO AND 
DATA_MODIFICACAO = (SELECT MAX(DATA_MODIFICACAO) FROM ARQUIVO WHERE ID_USUARIO = @ID_USUARIO);