-- RETORNA OS DADOS DA INSTITUICAO DE UM USUARIO 
SELECT I.ID_INSTITUICAO, I.NOME, I.CAUSA_SOCIAL, I.ENDERECO, I.ID_PLANO, I.DURACAO_PLANO, 
       I.DATA_AQUISICAO_PLANO, I.ESPACO_USUARIO_PLANO 
FROM INSTITUICAO I 
JOIN USUARIO U ON U.ID_INSTITUICAO = I.ID_INSTITUICAO 
WHERE U.ID_USUARIO = @ID_USUARIO;