-- VERIFICA SE UM USUARIO POSSUI UM ARQUIVO CRIADO
-- USADO PARA ABRIR O ARQUIVO MAIS RECENTE
SELECT COUNT(*) FROM ARQUIVO WHERE 
ID_USUARIO = @ID_USUARIO AND 
DATA_MODIFICACAO = (SELECT MAX(DATA_MODIFICACAO) FROM ARQUIVO WHERE ID_USUARIO = @ID_USUARIO);