-- RETORNA OS DADOS DA VERSAO ATUAL DE UM ARQUIVO NA TABELA 'HISTORICO_VERSIONAMENTO'
SELECT A.NOME, H.OPERACAO, H.DATA_VERSIONAMENTO, H.CONTEUDO, 
(SELECT COUNT(*) FROM HISTORICO_VERSIONAMENTO HV 
    WHERE HV.ID_ARQUIVO = H.ID_ARQUIVO AND HV.ID_HISTORICO <= H.ID_HISTORICO) AS VERSAO 
FROM HISTORICO_VERSIONAMENTO H 
LEFT JOIN ARQUIVO A ON A.ID_ARQUIVO = H.ID_ARQUIVO 
WHERE H.ID_ARQUIVO = @ID_ARQUIVO 
ORDER BY H.DATA_VERSIONAMENTO DESC, H.ID_HISTORICO DESC LIMIT 1;