-- CARREGA UM SESSAO DE ADMINISTRADOR COM OS DADOS DE UM ADMINISTRADOR
SELECT ID_ADMIN, ID_INSTITUICAO, LOGIN, EMAIL, SENHA, DATA_INGRESSO 
FROM ADMINISTRADOR 
WHERE EMAIL = @EMAIL AND 
      SENHA = @SENHA AND 
      ID_ADMIN = @ID_ADMIN;