-- RETORNA TODOS OS ARQUIVOS PERTENCENTES A UMA INSTITUICAO
SELECT I.NOME AS NOME_INSTITUICAO, A.ID_ARQUIVO, A.NOME AS NOME_ARQUIVO, 
       U.LOGIN AS USUARIO, A.PERMISSAO_ACESSO, A.DATA_MODIFICACAO, A.URL 
FROM ARQUIVO A 
LEFT JOIN USUARIO U ON A.ID_USUARIO = U.ID_USUARIO 
LEFT JOIN INSTITUICAO I ON I.ID_INSTITUICAO = U.ID_INSTITUICAO 
WHERE U.ID_INSTITUICAO = @ID_INSTITUICAO;