-- CRIA TABELA 'OPERAR'
CREATE TABLE OPERAR (
	ID_OPERACAO INT AUTO_INCREMENT,
    TIPO_OPERACAO VARCHAR(15) NOT NULL,
    DATA_OPERACAO DATE NOT NULL,
    ID_ARQUIVO INT NULL,
    ID_USUARIO INT,
    PRIMARY KEY(ID_OPERACAO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);