-- CRIA TABELA 'ARQUIVO'
CREATE TABLE ARQUIVO (
    ID_ARQUIVO INT AUTO_INCREMENT,
    ID_USUARIO INT,
    ID_ADMIN INT,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    PERMISSAO_ACESSO VARCHAR(100) NOT NULL,
    TAMANHO DOUBLE NOT NULL,
    DATA_MODIFICACAO DATE,
    LOCALIZACAO VARCHAR(100) NOT NULL,
    URL VARCHAR(100) NOT NULL,
    CONTEUDO VARCHAR(255),
    PRIMARY KEY(ID_ARQUIVO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_ADMIN) REFERENCES ADMINISTRADOR(ID_ADMIN)
);