-- CRIA TABELA 'HISTORICO_VERSIONAMENTO'
CREATE TABLE HISTORICO_VERSIONAMENTO (
    ID_HISTORICO INT AUTO_INCREMENT,
    ID_ARQUIVO INT,
    ID_USUARIO INT,
    OPERACAO VARCHAR(15),
    CONTEUDO VARCHAR(500),
    DATA_VERSIONAMENTO DATE,
    PRIMARY KEY(ID_HISTORICO)
);