-- CRIA TABELA 'COMENTAR'
CREATE TABLE COMENTAR (
    CONTEUDO TEXT NOT NULL,
    DATA_COMENTARIO DATE NOT NULL,
    USUARIO_ID INT,
    ARQUIVO_ID INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ARQUIVO_ID) REFERENCES ARQUIVO(ID_ARQUIVO) ON DELETE CASCADE
);