-- CRIA TABELA 'ADMINISTRADOR'
CREATE TABLE ADMINISTRADOR (
    ID_ADMIN INT AUTO_INCREMENT,
	ID_INSTITUICAO INT,
    LOGIN VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DATA_INGRESSO DATE,
    PRIMARY KEY(ID_ADMIN),
    FOREIGN KEY (ID_INSTITUICAO) REFERENCES INSTITUICAO(ID_INSTITUICAO)
);