DELIMITER $$
CREATE TRIGGER ATUALIZAR_ACESSO AFTER INSERT
ON COMPARTILHAR
FOR EACH ROW
BEGIN
	UPDATE ARQUIVOS
	SET DATA_MODIFICACAO = CURDATE()
  WHERE ID_ARQUIVO = NEW.ID_ARQUIVO;
    
END $$
DELIMITER ;
