DELIMITER $$

CREATE TRIGGER registrar_operacao
AFTER INSERT ON ARQUIVO
FOR EACH ROW
BEGIN
    IF EXISTS (SELECT 1 FROM ATIVIDADES_RECENTES WHERE FK_ID_ARQUIVO = NEW.ID_ARQUIVO) THEN
        UPDATE ATIVIDADES_RECENTES
        SET ULTIMA_VERSAO = CURDATE()
        WHERE FK_ID_ARQUIVO = NEW.ID_ARQUIVO;
    ELSE
        INSERT INTO ATIVIDADES_RECENTES (FK_ID_ARQUIVO, ULTIMA_VERSAO, ACESSO_PRIORITARIO)
        VALUES (NEW.ID_ARQUIVO, CURDATE(), NULL);
    END IF;
END $$

DELIMITER ;
