DELIMITER $$
CREATE TRIGGER registrar_update_file
AFTER UPDATE ON ARQUIVO
FOR EACH ROW
BEGIN
	DECLARE file_id INT;
    DECLARE user_id INT;

    SET file_id = OLD.ID_ARQUIVO;
    SET user_id = OLD.ID_USUARIO;
    
	INSERT INTO OPERAR (TIPO_OPERACAO, ID_ARQUIVO, ID_USUARIO, DATA_OPERACAO)
    VALUES ('UPDATE', file_id, user_id, CURDATE());
END $$
DELIMITER ;
