-- FAZ UM INSERT NA TABELA 'OPERAR' APOS DELETAR UM ARQUIVO NA TABELA 'ARQUIVO'
DELIMITER $$
CREATE TRIGGER registrar_delete_file
BEFORE DELETE ON ARQUIVO
FOR EACH ROW
BEGIN
    DECLARE file_id INT;
    DECLARE user_id INT;

    SET file_id = OLD.ID_ARQUIVO;
    SET user_id = OLD.ID_USUARIO;

    INSERT INTO OPERAR (TIPO_OPERACAO, ID_ARQUIVO, ID_USUARIO, DATA_OPERACAO)
    VALUES ('DELETE', file_id, user_id, CURDATE());
END$$
DELIMITER ;
