DELIMITER $$
CREATE TRIGGER REGISTRAR_OPERACAO AFTER INSERT
ON OPERAR
FOR EACH ROW
BEGIN
	UPDATE ATIVIDADES_RECENTES
    SET ULTIMA_VERSAO = NEW.DATA_OPERACAO
	WHERE FK_ID_ARQUIVO = NEW.ID_ARQUIVO;
    
    IF ROW_COUNT() = 0 THEN
        INSERT INTO ATIVIDADES_RECENTES (FK_ID_ARQUIVO, ULTIMA_VERSAO, ACESSO_PRIORITARIO)
        VALUES (NEW.ID_ARQUIVO, NEW.DATA_OPERACAO);
    END IF;
END $$
DELIMITER ;
