-- INSERE UM ADMINISTRADOR NA TABELA USUARIO
DELIMITER $$
CREATE TRIGGER registra_insert_usuario
AFTER INSERT ON ADMINISTRADOR
FOR EACH ROW
BEGIN
	INSERT INTO USUARIO (ID_USUARIO, ID_INSTITUICAO, LOGIN, SENHA, EMAIL, DATA_INGRESSO)
    VALUES (NEW.ID_ADMIN, NEW.ID_INSTITUICAO, NEW.LOGIN, NEW.SENHA, NEW.EMAIL, NEW.DATA_INGRESSO);
END $$
DELIMITER ;
