-- FAZ UM INSERT NA TABELA 'HISTORICO_VERSIONAMENTO' APOS O UPDATE DE UM ARQUIVO NA TABELA 'ARQUIVO'
DELIMITER $$
CREATE TRIGGER versionamento_update_file
AFTER UPDATE ON ARQUIVO
FOR EACH ROW
BEGIN
	DECLARE file_id INT;
    DECLARE user_id INT;

    SET file_id = NEW.ID_ARQUIVO;
    SET user_id = NEW.ID_USUARIO;
    
	INSERT INTO HISTORICO_VERSIONAMENTO (ID_ARQUIVO, ID_USUARIO, DATA_VERSIONAMENTO, OPERACAO, CONTEUDO)
    VALUES (file_id, user_id, NEW.DATA_MODIFICACAO, 'UPDATE', NEW.CONTEUDO);
END $$
DELIMITER ;