CREATE TABLE INSTITUICAO (
    ID_INSTITUICAO INT AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CAUSA_SOCIAL VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    ID_PLANO INT,
    DURACAO_PLANO VARCHAR(100),
    DATA_AQUISICAO_PLANO DATE,
    ESPACO_USUARIO_PLANO VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID_INSTITUICAO)
);